### PR TITLE
Update to Bevy 0.13

### PR DESCRIPTION
**Pull request by oscrim**

### CODE REVIEW

**Comment by nilaysavant** [comment]
Thanks for the PR! Will checkout and merge soon!

**Comment by nilaysavant** [comment]
I see 2 issues in particular in the `simple.rs` example:
- The lighting seems off. We can fix this by bumping up the intensity.
- In `Edit Mode`,  if we _drag_ the __vertex__ then the __connecting edges__ seem to have __gaps at the ends__. They go away if we _de-select_ and _re-select_ the `Mesh`.  
Screenshot 2024-04-13 at 9 58 03 PM

**Comment by nilaysavant** [comment]
Found the culprit for the `Edges` issue. 

Since you've changed to using `Cuboid` instead of `Box`, you also need to adjust the scale length for this in __Edit Mode__ to `edge_vec.length()` (same as how you've done it in the `indicators.rs`): 
https://github.com/nilaysavant/bevy_mesh_drawing/blob/6a52d81dc556422a83e46aca19de48f6f9850b71/crates/mesh_drawing/src/systems/edit_mode.rs#L389

**Comment by oscrim** [comment]
> Found the culprit for the `Edges` issue.
> 
> Since you've changed to using `Cuboid` instead of `Box`, you also need to adjust the scale length for this in **Edit Mode** to `edge_vec.length()` (same as how you've done it in the `indicators.rs`):
> 
> https://github.com/nilaysavant/bevy_mesh_drawing/blob/6a52d81dc556422a83e46aca19de48f6f9850b71/crates/mesh_drawing/src/systems/edit_mode.rs#L389

Ah I see, totally missed that. I also realized that the `EDGE_INDICATOR_WIDTH` will cause the width to be half of what they were prevoisly, do you want me to bump it up to 0.2 (as it was 0.1 previously)?

With regards to the lighting they have [changed the exposure](https://bevyengine.org/learn/migration-guides/0-12-to-0-13/#new-exposure-and-lighting-defaults-and-calibrate-examples) so all lighting values need to be changed, Ill increase the intensity of the light in the example

**Comment by nilaysavant** [comment]
> Ah I see, totally missed that. I also realized that the `EDGE_INDICATOR_WIDTH` will cause the width to be half of what they were prevoisly, do you want me to bump it up to 0.2 (as it was 0.1 previously)?

The edges are looking fine. I think its because I'm plugging it into the `scale`. So no need to update the width.

Overall looks good to me. Will merge it soon! Thanks again!

**Pull request merged**
